runtime: java17
instance_class: F1
includes:
  - secrets.yaml

env_variables:
  PRODUCTION: true

inbound_services:
  - warmup
automatic_scaling:
  min_idle_instances: 1
  min_instances: 1
  max_idle_instances: 1
  max_instances: 1
