application:
  production: ${PRODUCTION:false}

server:
  port: ${PORT:8080}

springdoc:
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    enabled: true
    try-it-out-enabled: true
    persist-authorization: true
  webjars:
    prefix:

spring:
  application:
    version: @project.version@
  webflux:
    base-path: ${BASE_URL_PATH:/}
  profiles:
    active:
      - default
      - db
    include: # Add all modules here, comment to disable them
      - external-config
      # - item-collection-tracker # TODO: re-import or remove
      - notion-assistant
      # - river-crossing
