#
name: Create and publish a Docker image

on:
  workflow_dispatch:
  release:
    types: [ created ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: write
      attestations: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.4

#      - name: Set up JDK 21
#        uses: actions/setup-java@v4.2.1
#        with:
#          java-version: '21'
#          distribution: 'temurin'
#          settings-path: ${{ github.workspace }} # location for the settings.xml file
#
#      - name: Build with Maven
#        run: mvn -B package --file pom.xml -s $GITHUB_WORKSPACE/settings.xml
#        env:
#          GITHUB_TOKEN: ${{ github.token }}

      - name: maven-settings-action
        uses: s4u/maven-settings-action@v3.0.0
        with:
          path: '${{ github.workspace }}/settings.xml'
          githubServer: false
          servers: |
            [{
              "id": "github",
              "username": "${{ secrets.PUBLISH_USERNAME }}",
              "password": "${{ secrets.PUBLISH_TOKEN }}"
            }]

      - name: Log in to the Container registry
        uses: docker/login-action@v3.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: '${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}'

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1.1.0
        with:
          subject-name: '${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ env.IMAGE_NAME }}'
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
